[package]
name = "audio_welder"
version = "0.1.0"
edition = "2021"

[build-dependencies]
crate_manager={ git="https://github.com/SuccessfullyFailed/crate_manager.git" }

[dependencies]
hound="3.5.0"
cpal="0.15.2"
image="0.23.14"